"""Create All

Revision ID: f1e156f79381
Revises:
Create Date: 2025-11-14 18:20:16.269447

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f1e156f79381"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	sa.Enum("pending", "completed", "failed", name="paymentstatus").create(
		op.get_bind()
	)
	op.create_table(
		"admins",
		sa.Column(
			"super_admin",
			sa.Boolean(),
			server_default=sa.text("false"),
			nullable=False,
			comment="Is this admin a super admin",
		),
		sa.Column(
			"is_active",
			sa.Boolean(),
			server_default=sa.text("true"),
			nullable=False,
			comment="Whether the admin account is active",
		),
		sa.Column("id", sa.BigInteger(), nullable=False),
		sa.Column(
			"created_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.Column(
			"updated_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.PrimaryKeyConstraint("id", name=op.f("admins_pkey")),
	)
	op.create_table(
		"users",
		sa.Column(
			"username",
			sa.String(length=20),
			nullable=True,
			comment="Telegram username",
		),
		sa.Column(
			"full_name",
			sa.String(length=100),
			nullable=False,
			comment="User's full name",
		),
		sa.Column(
			"utm_source",
			sa.String(length=20),
			nullable=True,
			comment="UTM source parameter",
		),
		sa.Column(
			"utm_campaign",
			sa.String(length=20),
			nullable=True,
			comment="UTM campaign parameter",
		),
		sa.Column(
			"utm_content",
			sa.String(length=20),
			nullable=True,
			comment="UTM content parameter",
		),
		sa.Column(
			"is_connected",
			sa.Boolean(),
			server_default=sa.text("false"),
			nullable=False,
			comment="Whether user is connected to the closed channel",
		),
		sa.Column(
			"connected_at",
			sa.DateTime(timezone=True),
			nullable=True,
			comment="When user connected to the closed channel",
		),
		sa.Column(
			"reminders_sent",
			sa.SmallInteger(),
			server_default=sa.text("0"),
			nullable=False,
			comment="Number of reminder messages already sent",
		),
		sa.Column(
			"blocked_the_bot",
			sa.Boolean(),
			server_default=sa.text("false"),
			nullable=False,
			comment="Whether user has blocked the bot",
		),
		sa.Column(
			"notes",
			sa.Text(),
			nullable=True,
			comment="Additional notes about the user",
		),
		sa.Column("id", sa.BigInteger(), nullable=False),
		sa.Column(
			"created_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.Column(
			"updated_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.PrimaryKeyConstraint("id", name=op.f("users_pkey")),
	)
	op.create_table(
		"payments",
		sa.Column(
			"user_id",
			sa.BigInteger(),
			nullable=False,
			comment="Reference to User",
		),
		sa.Column(
			"currency",
			sa.String(length=10),
			nullable=False,
			comment="Currency of the payment",
		),
		sa.Column("amount", sa.Float(), nullable=False, comment="Amount paid"),
		sa.Column(
			"status",
			postgresql.ENUM(
				"pending",
				"completed",
				"failed",
				name="paymentstatus",
				create_type=False,
			),
			nullable=False,
			comment="Status of the payment",
		),
		sa.Column(
			"pay_url",
			sa.String(length=100),
			nullable=False,
			comment="Payment URL",
		),
		sa.Column(
			"paid_at",
			sa.DateTime(timezone=True),
			nullable=True,
			comment="Timestamp when payment was completed",
		),
		sa.Column("fee", sa.Float(), nullable=True, comment="Transaction fee"),
		sa.Column("id", sa.BigInteger(), nullable=False),
		sa.Column(
			"created_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.Column(
			"updated_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.ForeignKeyConstraint(
			["user_id"], ["users.id"], name=op.f("payments_user_id_fkey")
		),
		sa.PrimaryKeyConstraint("id", name=op.f("payments_pkey")),
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_table("payments")
	op.drop_table("users")
	op.drop_table("admins")
	sa.Enum("pending", "completed", "failed", name="paymentstatus").drop(
		op.get_bind()
	)
	# ### end Alembic commands ###
